cameras:
  static:
    _target_: spaceman.envs.genesis_env.GenesisSim
    name: static
    fov: 40
    aspect: 1
    nearval: 0.01
    farval: 10
    width: 200
    height: 200
    look_at:
    - 0
    - 0
    - 0.5
    look_from:
    - -2.5
    - -3.0
    - 2.5
  gripper:
    _target_: spaceman.envs.camera.gripper_camera.GripperCamera
    name: gripper
    fov: 70
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 84
    height: 84
    look_at:
    - 0.10000000149011612
    - -1.0
    - 0.0
    look_from:
    - 0.07000000029802322
    - 0.10000000149011612
    - -0.10000000149011612
    up_vector:
    - 1.0
    - 0.0
    - 0.0
load_dir: datasets/episode_20260429_125511/
data_path: data
save_dir: null
show_gui: false
processes: 16
max_episode_frames: 53
save_body_infos: true
set_static_cam: true
scene:
  _target_: vr_env.scene.play_table_scene.PlayTableScene
  _recursive_: false
  name: robot_assisted_docking_task
  robot_base_position:
  - -0.30000001192092896
  - 0.0
  - 0.0
  robot_base_orientation:
  - 0.0
  - 0.0
  - 0.0
  robot_initial_joint_positions:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  objects:
    movable_objects:
      starlink:
        file: "/home/robot/\u684C\u9762/spaceman_core/src/assets/urdf/starlink/urdf/starlink.urdf"
        initial_pos:
        - 0.0
        - 0.0
        - 0.0
        initial_orn:
        - 0.0
        - 0.0
        - 0.0
robot:
  _target_: spaceman.robots.starlink.Robot
  name: starlink
  urdf_path: "/home/robot/\u684C\u9762/spaceman_core/src/assets/urdf/starlink/urdf/starlink.urdf"
  euler_obs: true
  gripper_obs: true
  joint_pos_obs: true
  tcp_pos_obs: true
  tcp_quat_obs: true
  base_pos_obs: true
  base_quat_obs: true
  gripper_value_obs: true
episode_metadata:
  episode_id: '20260429_125511'
  num_frames: 53
  action_dim: 7
  robot_obs_dim: 19
  scene_obs_dim: 6
  rgb_static_shape:
  - 53
  - 200
  - 200
  - 3
  rgb_gripper_shape:
  - 53
  - 84
  - 84
  - 3
  success: true
  timestamp: '2026-04-29T12:56:06.531255'
